/*
Do not use database modifying (ALTER DATABASE), creating (CREATE DATABASE) or switching (USE) statements 
in this file.
*/
/*
create database BookLibrary
go

use BookLibrary
go
*/
-- 1-N veza
create table Genre (
	Id int primary key identity,
	[Name] nvarchar(50) not null
)
go

create table Book (
	Id int primary key identity,
	ISBN nvarchar(17) not null,
	[Name] nvarchar(255) not null,
	Author nvarchar(255) not null,
	[Description] nvarchar(max),
	PublicationDate date,
	GenreId int foreign key references Genre(Id) not null,
)
go

create table [Location] (
	Id int primary key identity,
	[Name] nvarchar(50) not null,
)
go

create table [User] (
	Id int primary key identity,
	Username nvarchar(31) not null,
	PwdHash nvarchar(255) not null, -- Salt also stored
    Role nvarchar(50) not null default 'User',
	Email nvarchar(255),
	FirstName nvarchar(50),
	LastName nvarchar(50),
	Phone nvarchar(50)
)
go

-- M-N veza
create table BookLocation (
	Id int primary key identity,
	BookId int foreign key references Book(Id) not null,
	LocationId int foreign key references [Location](Id) not null,
)
go

-- M-N veza
create table UserReservation (
	Id int primary key identity,
	[Status] int default 0 not null,
	[Date] datetime default getdate(),
	UserId int foreign key references [User](Id) not null,
	BookId int foreign key references Book(Id) not null
)
go

-- M-N veza
create table UserReview (
	Id int primary key identity,
	Rating int check (Rating >= 1 and Rating <= 5) not null,
	[Text] nvarchar(max),
	BookId int foreign key references Book(Id) not null,
	UserId int foreign key references [User](Id) not null
)
go

create table BookLog (
	Id int primary key identity,
	[Timestamp] datetime default getdate() not null,
	[Level] int not null,
	[Message] nvarchar(max) not null,
)
go

-- LOCAL ADMIN USER (for ease)
insert into [User] (Username, PwdHash, Email, Role)
values (
    'admin',
    '$argon2id$v=19$m=65536,t=3,p=1$2bRp7ir3PTcdxOhsgtHArA$DxXirDpASmqTTp3YWCe47uevElZqjMpXYy12e6Ur8B4',
    'admin@localhost',
    'Admin'
)
go

/*
	BOOK INSERT QUERIES
	GENERATED BY CHATGPT FOR THIS STRUCTURE
*/

INSERT INTO Genre ([Name]) VALUES
(N'Fantasy'),
(N'Science Fiction'),
(N'Mystery'),
(N'Romance'),
(N'Horror'),
(N'Thriller'),
(N'Historical'),
(N'Non-fiction'),
(N'Biography'),
(N'Adventure');

-- Insert Books
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-65125-141-4', N'Serious inside else memory.', N'Richard Turner', N'On traditional measure example sense peace. Would mouth relate own chair. Role together range line.', '2023-09-18', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-63075-902-4', N'Ability management test during foot.', N'Cheryl Bradley', N'Sort language ball floor. Your majority feeling fact by four two.', '1981-06-29', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-86465-323-8', N'Theory type successful.', N'Tammy Fernandez', N'Situation talk despite stage. Own available buy country store build before.', '2012-06-01', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-28316-873-1', N'Per structure attorney author.', N'Jeffrey Brown', N'Others record hospital. Grow rule stuff truth college. Whom around put suddenly garden.', '1985-10-27', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-79804-822-9', N'Real leader bad school name.', N'Philip Olson', N'Knowledge else citizen month.', '2021-05-14', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-22945-847-1', N'Partner couple part cup few.', N'Catherine Alvarez', N'Long dream answer conference. Rock few structure federal board night loss.', '1975-12-01', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-83375-203-5', N'Hour million.', N'John Richards', N'Base detail yourself one coach court. Ask tell reduce total.', '2021-08-25', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-90070-755-3', N'There many true follow.', N'Mr. Michael Harris DDS', N'Future while together. Along chance either six success on.', '2001-05-23', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-68024-986-8', N'Maybe off question source serious.', N'Nicole Bullock MD', N'Political camera expert stop. Walk loss cell three.', '1995-05-17', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-81919-114-1', N'Million size country.', N'Jill Sherman', N'Between similar safe air. Issue indicate market ten foot education good. Grow ahead girl act.', '1991-03-24', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-90202-605-5', N'Cost both general.', N'Beverly Levy', N'List fall view when player contain. Bill ok choose today. Source firm drug senior.', '1992-04-05', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-18255-295-9', N'Plan PM more heavy.', N'Victor Valenzuela', N'A huge three. Know second government the pull cultural.', '2003-08-11', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-28677-922-8', N'Executive care mission.', N'Brian Sosa', N'Seem explain black leave. Himself former possible reach challenge value.', '1977-08-24', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-20544-427-8', N'Plan that hair.', N'Megan Hall', N'Beautiful than seem sign third in approach recent. Upon value ok majority region democratic entire.', '1984-12-07', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-49511-664-4', N'Skill quite.', N'Jennifer Morse', N'Past Republican common increase.
They young according movement into. Business population brother.', '2018-07-31', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-53614-934-8', N'Speech theory.', N'Christopher Esparza', N'Sit simple notice receive degree. Staff service government opportunity.', '2020-11-12', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-81726-701-4', N'Employee public figure.', N'Joshua Oconnor', N'Against physical agency and difficult president. Start general professional career.', '2013-10-23', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-88156-917-6', N'Important hope about.', N'Sean Palmer', N'Form style star east. What to sea.', '2006-07-22', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-41733-397-2', N'Medical class send.', N'Robert Blackburn', N'Morning explain light alone mother.', '1992-06-08', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-14321-727-4', N'Break word source.', N'Dana Craig', N'We lose water. Section could nature interest wear. Morning as police often.', '2013-09-17', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-21773-795-2', N'Guess we no in.', N'Regina Perez', N'More walk quite piece physical market.', '2004-06-02', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-20518-816-8', N'Wait education think similar.', N'Ann Johnson', N'Dark huge itself play pull.
Let stop camera report foreign agency list miss.
Not girl above course.', '1986-06-20', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-46127-634-3', N'Throughout treat relate.', N'Misty Blair', N'Statement reality recently. Wear general one bar nice spend. Son foreign remember site military.', '2010-12-02', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-64974-693-4', N'Remember tree care.', N'Amy Miller', N'Someone treatment over some collection. Impact key page per.', '2002-11-09', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-96539-756-5', N'Real to follow so second.', N'Karen Hodge', N'So teach energy possible believe step. Grow better why child might source. A front war.', '1991-08-04', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-90318-218-7', N'Difficult there leg theory.', N'Karl Smith', N'Hair describe hundred candidate. Probably whom it job likely different house.', '2025-02-15', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-34953-348-0', N'Item bit leave left.', N'John Moore', N'Both happy central group line million approach. Computer on fast play fact.', '1989-07-01', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-38896-480-2', N'Direction moment standard.', N'Stephen Fitzgerald', N'North trouble upon beautiful open free. Them although per environmental medical nearly hour.', '2003-04-13', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-18151-203-2', N'Begin lot sport father growth.', N'Matthew Brown', N'Next according television next sense make real use. Girl sister their rate drop marriage worker.', '1991-02-22', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-85217-749-8', N'Very score loss.', N'Heather Cruz', N'Husband matter likely prevent. Place grow everyone win should research.', '2001-10-31', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-13499-227-3', N'Message woman with not.', N'Megan Shaw', N'Fire range begin first through. Star issue any side image. Customer force both something hair.', '2011-12-02', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-25688-500-1', N'Unit dinner indeed.', N'Aaron Clark', N'West agreement girl happen front law care military.', '2009-12-13', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-14769-720-0', N'Build black treat buy.', N'Julie Gibson', N'Indicate help north friend. Law go simple improve language. Need when simple.', '2010-08-14', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-26239-590-3', N'Pull watch choice already thank.', N'Pamela Mcdonald', N'Many cold another way sign fund. Could foreign mind myself surface old charge.', '1999-08-23', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-81334-535-9', N'Hospital wrong fish yeah.', N'Daniel Wilson', N'Week remain decide happy another image. Take one them in.', '2017-05-14', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-19175-326-1', N'Fine seat should dream.', N'Alyssa Boyer', N'Its professor while seven.
Relationship easy picture enough.', '1982-02-20', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-67156-284-0', N'Night western serious edge bit.', N'Zachary Anderson', N'Subject development best student describe concern professional.', '1981-01-17', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-15161-710-1', N'Final relationship wear along.', N'Ebony Wilson', N'Mention get last increase mother. But order leg food fast pick.', '1994-12-10', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-44096-467-7', N'Situation eat.', N'Kellie Green', N'Industry old effect fine speak majority. Remain interest college anything relationship local air.', '1979-05-09', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-98164-308-0', N'Remember take ground.', N'Daniel Turner', N'Necessary economy agree discussion. Understand relate church serve can street.', '1979-08-17', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-54867-642-4', N'Cold measure defense mouth.', N'Cameron Miller Jr.', N'Which worker second. Purpose world win product election baby seven.', '2023-01-31', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-67974-781-2', N'Give point herself official.', N'Kathryn Craig', N'While door statement scene teach. Old site record should.', '2017-01-03', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-99296-519-9', N'Measure only wait technology town.', N'Steven Johnson', N'Be financial plan phone step country article. Firm woman section magazine.', '1995-05-27', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-95057-465-6', N'Range international.', N'Brian Kelly', N'Account part wind well. Impact six loss agree. Star be hot often worry any include try.', '2023-03-30', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-83478-807-0', N'Image throughout western.', N'Mrs. Sara Johns', N'Walk camera debate western store office explain. Deep range ten television model.', '1979-08-22', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-54029-856-0', N'Health effect.', N'John Nichols', N'Firm himself idea lose. Million trade century hundred themselves finish.', '2020-12-13', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-27673-345-7', N'Level generation since also himself.', N'Gloria Hunt', N'Baby book itself people nation million born. Now always hand.', '1986-08-08', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-47732-789-5', N'Receive rate oil defense.', N'Jesse Dean', N'Kid official within nothing tend pick mention hot. Herself drive effort drop onto until.', '2010-03-16', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-27346-832-4', N'Government image room.', N'Tyler Munoz', N'Learn economy explain main sport summer sea. Approach trip throughout free civil entire.', '2025-01-24', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-95305-182-0', N'Before open hot.', N'Steven Dunlap', N'Say about century debate officer about camera machine. Me wear prove.', '2019-09-24', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-53830-263-3', N'Might catch.', N'Suzanne Thomas', N'Crime social school enter wind heavy anything. Save himself call report must charge.', '2002-01-06', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-59630-827-9', N'Best I.', N'Julie Valdez', N'Do believe her attorney stock.', '2016-05-28', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-62725-992-9', N'Go woman.', N'Michaela Johnson', N'Democratic radio stay century law before. Structure face forget result professor.', '1976-08-05', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-31715-556-1', N'Executive military plan school.', N'Jordan Flores', N'Tough subject customer far recently prepare. House central baby picture choice could.', '2023-03-15', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-68505-640-7', N'Soldier class personal quickly ok.', N'Kelly Blevins', N'Present defense become result easy.', '1985-03-30', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-10009-139-7', N'Ago whom language place.', N'Katrina Ingram', N'Boy sing threat bill pattern scientist early. Range know close election.', '2018-12-02', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-71196-151-6', N'Open wife.', N'Diane Palmer', N'Pattern story term show industry.', '2015-04-09', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-92980-185-2', N'Few natural fight stand one.', N'Hannah Coleman', N'Assume dinner former heavy person. Consumer through theory simply. Wall allow power condition.', '2006-10-09', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-98934-527-5', N'Art practice.', N'Colleen Fitzpatrick', N'Until help attention American some before according. Around almost amount themselves test.', '2005-09-16', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-11873-834-0', N'Road collection big talk.', N'Jennifer Anderson', N'Whole stage the common prevent. Customer plan maybe manager place fly.', '2004-01-15', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-22816-295-1', N'Establish son turn another wonder.', N'Whitney Wong', N'Dinner write usually team remember.', '2002-11-28', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-49638-386-2', N'On stand trip.', N'Joshua Mathews', N'Then probably or which white get bring. Industry control thank.', '2024-06-03', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-61995-742-1', N'Education red citizen.', N'Elizabeth Hinton', N'You economy huge miss. Fly rock make build painting either.', '1977-02-10', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-69372-919-1', N'Manage special.', N'Hannah Ruiz', N'Speak let guy son. Gas class wish relate sound market best.', '2023-06-26', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-95664-633-5', N'Around both place.', N'Lisa Davis', N'Oil describe section few stay top most. Shake phone positive idea throughout.', '1995-12-14', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-46491-971-0', N'Speak cause compare difficult.', N'Calvin Duran', N'Share body fly find.
Push serve rule thus. Western worry week people worker time.', '1996-11-29', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-36966-797-4', N'Third since laugh.', N'Katherine Lamb', N'Third option chair decide. Hand benefit major friend through data.', '2005-09-14', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-58089-681-0', N'National senior how artist.', N'Stephen Lang', N'Form great education training see we.', '1986-06-15', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-94429-569-6', N'Risk exactly speak.', N'Heather Gray', N'Represent performance cold if project. Statement unit in baby.', '1987-01-15', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-33368-312-6', N'Senior current fact scientist.', N'Brittany Singleton', N'Free finally national difficult field off government forget.', '2014-05-14', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-11166-241-2', N'Mrs possible add analysis.', N'James Harper', N'Full road nothing defense customer.', '2001-03-28', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-54238-908-5', N'Improve hit nice.', N'Marcus Cervantes', N'Modern democratic human difference rock music check close.
Box people point month smile national.', '1979-06-18', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-91335-136-0', N'Operation cover program.', N'Debra Watson', N'Yet recent grow crime. Discussion without current rate business worker.', '2021-04-02', 5);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-29584-697-4', N'Good challenge business rule sometimes.', N'Carrie Lam', N'Oil drive local cover interview us up. Social cell stage goal.', '2002-03-09', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-81890-232-4', N'Factor blue walk.', N'Tonya Hooper', N'Any worry include happy thought early president.', '1976-11-10', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-41418-149-4', N'Change message paper easy.', N'Stephanie Cordova', N'Mission recently value expert thing bed among. Else represent detail open future rich.', '1999-05-24', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-19288-409-6', N'With travel responsibility cut.', N'Mark Ryan', N'Plan high civil tree action. Coach yard treat. Have approach difference difficult.', '1982-01-24', 6);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-64358-211-1', N'Black over before.', N'Regina Hamilton', N'Add pattern player personal which reflect. Camera federal family I miss. Leader note understand.', '1975-11-05', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-72128-445-5', N'Subject yet.', N'Kevin Grant', N'Simply wait similar blood really child lead.', '2009-09-12', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-25205-816-7', N'Five establish per.', N'William Bailey', N'Store community together far enough ability citizen.', '2014-12-02', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-0-49571-443-2', N'Soon four once.', N'David Singh', N'Model adult stand five modern there. No air run win.', '1979-06-02', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-9-59226-925-1', N'Career wind.', N'Justin Smith', N'Watch choice cause natural. Home hard general nor administration open. Happen show garden.', '1987-08-02', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-35957-867-3', N'Language ball someone environmental.', N'Sabrina Gutierrez', N'Citizen least organization probably only. She half air important truth.', '2016-03-15', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-11029-200-6', N'Work upon article compare.', N'Erica Gordon', N'Determine someone hit. Reveal player soon current by.', '1991-10-15', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-47987-559-7', N'Space water realize market.', N'Amanda Velez', N'Everything war he including. Require night personal sure whether visit.', '1992-05-26', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-65448-185-5', N'Gas right yes American call.', N'Rita Watson', N'Event under same commercial. Itself tax activity mission industry skin.', '1997-11-17', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-4-86707-895-2', N'Perform whose.', N'Shaun Turner', N'Walk live skill course laugh. Owner strategy identify involve. Cold right must body doctor tough.', '1978-08-31', 7);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-56991-217-1', N'Imagine perhaps.', N'Mathew Mccullough', N'Inside somebody analysis fund. Give source share budget. Theory moment better.', '1983-06-10', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-69193-870-3', N'Its pull inside.', N'Cheryl Johnson', N'Red score speak answer. Hit look lay score inside. Discuss ask team maybe future stay rich.', '2003-11-07', 2);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-62160-362-3', N'Term each mission hair.', N'Lauren Alvarez', N'Police space specific enter. Hotel agent clear art international time.', '1980-06-18', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-91712-249-1', N'Chair cover care.', N'Alyssa Hill', N'Herself space wife. Although president across human. Without finish weight theory.', '1981-04-11', 4);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-59549-470-8', N'One sort blue since long.', N'Tanner Johnson', N'Step inside so section reveal structure chair. Impact no almost international.', '1984-08-31', 3);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-88150-599-2', N'Music rest until new enter.', N'Melissa Mitchell', N'Cover feel debate. About into nearly water realize.', '2000-12-11', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-6-93671-796-6', N'Forget crime resource.', N'Kevin Johnson', N'Day claim contain discuss bad. How institution seek certainly explain. Pretty note fear him party.', '1989-01-12', 9);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-7-99039-430-7', N'Daughter start quality if.', N'Christopher Hays', N'Once should real Mrs lay new everyone.
Goal join reduce allow eat side.', '1985-04-14', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-3-81147-724-3', N'Seven woman throughout describe.', N'Susan Barrett', N'Major charge author themselves other today PM. Should enough act end value new.', '2004-03-11', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-5-51714-937-5', N'Effect check head huge standard.', N'Robin Ortiz', N'Top opportunity wish race book. Name have TV environment.', '2001-03-02', 1);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-8-29446-995-4', N'Personal Democrat.', N'Christina Mcdonald', N'Whose thus goal test finish responsibility. Peace the agency to sell positive blood home.', '1982-06-10', 10);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-2-59676-696-4', N'Nature another check group indeed.', N'Randall Ponce', N'Little Mr population add age letter religious. Money purpose TV between camera.', '2019-10-22', 8);
INSERT INTO Book (ISBN, [Name], Author, [Description], PublicationDate, GenreId) VALUES ('978-1-21094-628-0', N'Set offer.', N'Mary West', N'Interesting shake wife all upon. Him dog onto movement we window. There reality size move red join.', '1989-12-31', 2);
